import { FontPairing } from "@/types/pairing";

export const curatedPairings: FontPairing[] = [
  {
    id: "playfair-opensans",
    primary: { family: "Playfair Display", weight: 700 },
    secondary: { family: "Open Sans", weight: 400 },
    tags: ["elegant", "editorial"],
    useCase: "Luxury brands, editorial magazines",
    previewContent: {
      heading: "Timeless Elegance",
      subheading: "Where Classic Meets Modern",
      body: "A sophisticated pairing that combines the refined serif elegance of Playfair Display with the clean readability of Open Sans.",
      button: "Explore Collection",
    },
  },
  {
    id: "montserrat-merriweather",
    primary: { family: "Montserrat", weight: 700 },
    secondary: { family: "Merriweather", weight: 400 },
    tags: ["modern", "corporate"],
    useCase: "Corporate websites, tech startups",
    previewContent: {
      heading: "Modern Professional",
      subheading: "Clean and Trustworthy",
      body: "Montserrat's geometric clarity pairs beautifully with Merriweather's readable serif for professional communication.",
      button: "Get Started",
    },
  },
  {
    id: "raleway-lora",
    primary: { family: "Raleway", weight: 600 },
    secondary: { family: "Lora", weight: 400 },
    tags: ["elegant", "editorial"],
    useCase: "Blogs, lifestyle brands",
    previewContent: {
      heading: "Refined Simplicity",
      subheading: "Elegant Typography",
      body: "Raleway's sophisticated sans-serif complements Lora's calligraphic serif for a warm, approachable feel.",
      button: "Read More",
    },
  },
  {
    id: "poppins-lato",
    primary: { family: "Poppins", weight: 700 },
    secondary: { family: "Lato", weight: 400 },
    tags: ["modern", "corporate"],
    useCase: "SaaS products, modern web apps",
    previewContent: {
      heading: "Bold and Clear",
      subheading: "Modern Web Design",
      body: "Poppins brings geometric strength while Lato ensures comfortable reading across all devices.",
      button: "Sign Up Free",
    },
  },
  {
    id: "oswald-roboto",
    primary: { family: "Oswald", weight: 600 },
    secondary: { family: "Roboto", weight: 400 },
    tags: ["modern", "corporate"],
    useCase: "News sites, bold brands",
    previewContent: {
      heading: "Strong Impact",
      subheading: "Bold Statements",
      body: "Oswald's condensed strength creates powerful headlines, while Roboto handles body text with clarity.",
      button: "Learn More",
    },
  },
  {
    id: "cormorant-garamond-source",
    primary: { family: "Cormorant Garamond", weight: 600 },
    secondary: { family: "Source Sans Pro", weight: 400 },
    tags: ["elegant", "editorial"],
    useCase: "Luxury fashion, high-end publications",
    previewContent: {
      heading: "Sophisticated Luxury",
      subheading: "Refined Aesthetics",
      body: "Cormorant Garamond's classic elegance meets Source Sans Pro's modern clarity for premium brands.",
      button: "Discover",
    },
  },
  {
    id: "bebas-nunito",
    primary: { family: "Bebas Neue", weight: 400 },
    secondary: { family: "Nunito", weight: 400 },
    tags: ["playful", "modern"],
    useCase: "Creative agencies, event websites",
    previewContent: {
      heading: "Creative Energy",
      subheading: "Bold and Friendly",
      body: "Bebas Neue's condensed impact pairs with Nunito's rounded friendliness for energetic designs.",
      button: "Join Us",
    },
  },
  {
    id: "lora-roboto",
    primary: { family: "Lora", weight: 600 },
    secondary: { family: "Roboto", weight: 400 },
    tags: ["elegant", "editorial"],
    useCase: "Blogs, content sites",
    previewContent: {
      heading: "Readable Elegance",
      subheading: "Comfortable Reading",
      body: "Lora's calligraphic serif creates warm headings while Roboto ensures excellent readability.",
      button: "Continue Reading",
    },
  },
  {
    id: "inter-crimson",
    primary: { family: "Inter", weight: 700 },
    secondary: { family: "Crimson Text", weight: 400 },
    tags: ["modern", "editorial"],
    useCase: "Modern publications, tech blogs",
    previewContent: {
      heading: "Contemporary Classic",
      subheading: "Modern Typography",
      body: "Inter's optimized screen rendering pairs with Crimson Text's traditional serif for balanced design.",
      button: "Subscribe",
    },
  },
  {
    id: "space-grotesk-crimson",
    primary: { family: "Space Grotesk", weight: 700 },
    secondary: { family: "Crimson Pro", weight: 400 },
    tags: ["modern", "playful"],
    useCase: "Creative portfolios, modern brands",
    previewContent: {
      heading: "Geometric Modern",
      subheading: "Fresh and Dynamic",
      body: "Space Grotesk's unique character meets Crimson Pro's readable serif for contemporary appeal.",
      button: "View Portfolio",
    },
  },
  {
    id: "dm-serif-display-dm-sans",
    primary: { family: "DM Serif Display", weight: 400 },
    secondary: { family: "DM Sans", weight: 400 },
    tags: ["elegant", "corporate"],
    useCase: "Professional services, law firms",
    previewContent: {
      heading: "Professional Authority",
      subheading: "Trusted Expertise",
      body: "DM Serif Display's strong presence pairs with DM Sans for cohesive professional communication.",
      button: "Contact Us",
    },
  },
  {
    id: "work-sans-crimson",
    primary: { family: "Work Sans", weight: 700 },
    secondary: { family: "Crimson Pro", weight: 400 },
    tags: ["modern", "corporate"],
    useCase: "Corporate websites, documentation",
    previewContent: {
      heading: "Clear Communication",
      subheading: "Professional Clarity",
      body: "Work Sans provides excellent readability while Crimson Pro adds warmth to long-form content.",
      button: "Download",
    },
  },
  {
    id: "fraunces-libre",
    primary: { family: "Fraunces", weight: 700 },
    secondary: { family: "Libre Franklin", weight: 400 },
    tags: ["elegant", "editorial"],
    useCase: "Editorial sites, magazines",
    previewContent: {
      heading: "Editorial Excellence",
      subheading: "Magazine Quality",
      body: "Fraunces brings editorial sophistication while Libre Franklin ensures comfortable reading.",
      button: "Read Article",
    },
  },
  {
    id: "archivo-black-archivo",
    primary: { family: "Archivo Black", weight: 400 },
    secondary: { family: "Archivo", weight: 400 },
    tags: ["modern", "playful"],
    useCase: "Bold brands, creative projects",
    previewContent: {
      heading: "Bold Statements",
      subheading: "Strong Personality",
      body: "Archivo Black's condensed power pairs with Archivo's readable sans for impactful designs.",
      button: "Explore",
    },
  },
  {
    id: "libre-baskerville-libre-franklin",
    primary: { family: "Libre Baskerville", weight: 700 },
    secondary: { family: "Libre Franklin", weight: 400 },
    tags: ["elegant", "editorial"],
    useCase: "Classic publications, academic sites",
    previewContent: {
      heading: "Classic Typography",
      subheading: "Timeless Design",
      body: "Libre Baskerville's traditional serif pairs with Libre Franklin for cohesive editorial design.",
      button: "Learn More",
    },
  },
  {
    id: "rubik-karla",
    primary: { family: "Rubik", weight: 700 },
    secondary: { family: "Karla", weight: 400 },
    tags: ["modern", "playful"],
    useCase: "Modern apps, friendly brands",
    previewContent: {
      heading: "Friendly Modern",
      subheading: "Approachable Design",
      body: "Rubik's rounded geometry pairs with Karla's friendly sans for approachable, modern designs.",
      button: "Get Started",
    },
  },
  {
    id: "cinzel-lato",
    primary: { family: "Cinzel", weight: 600 },
    secondary: { family: "Lato", weight: 400 },
    tags: ["elegant", "corporate"],
    useCase: "Luxury brands, high-end services",
    previewContent: {
      heading: "Luxurious Elegance",
      subheading: "Premium Experience",
      body: "Cinzel's classical elegance meets Lato's modern clarity for sophisticated brand communication.",
      button: "Explore",
    },
  },
  {
    id: "josefin-sans-lora",
    primary: { family: "Josefin Sans", weight: 600 },
    secondary: { family: "Lora", weight: 400 },
    tags: ["elegant", "modern"],
    useCase: "Fashion brands, lifestyle sites",
    previewContent: {
      heading: "Refined Style",
      subheading: "Contemporary Elegance",
      body: "Josefin Sans' geometric elegance pairs with Lora's calligraphic serif for refined aesthetics.",
      button: "Shop Now",
    },
  },
  {
    id: "anton-roboto",
    primary: { family: "Anton", weight: 400 },
    secondary: { family: "Roboto", weight: 400 },
    tags: ["playful", "modern"],
    useCase: "Sports brands, bold campaigns",
    previewContent: {
      heading: "Maximum Impact",
      subheading: "Bold and Direct",
      body: "Anton's condensed power creates striking headlines while Roboto handles body text clearly.",
      button: "Join Now",
    },
  },
  {
    id: "spectral-crimson",
    primary: { family: "Spectral", weight: 700 },
    secondary: { family: "Crimson Pro", weight: 400 },
    tags: ["elegant", "editorial"],
    useCase: "Literary sites, academic publications",
    previewContent: {
      heading: "Literary Excellence",
      subheading: "Academic Quality",
      body: "Spectral's refined serif pairs with Crimson Pro for sophisticated editorial and academic content.",
      button: "Read More",
    },
  },
];

